[package]
name = "prod_axum"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features=["full"] }
axum = "0.7.7"
serde = { version = "1", features=["derive"]}
serde_json = "1"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"